### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by BucherLi** [zhanzecheng/Chinese_segment_augment#10]
运行报了这个错
#python3 demo_run.py 
Traceback (most recent call last):
  File "demo_run.py", line 44, in <module>
    stopwords = get_stopwords()
  File "/data/home/tengenli/Chinese_segment_augment/utils.py", line 13, in get_stopwords
    stopword = [line.strip() for line in f]
  File "/data/home/tengenli/Chinese_segment_augment/utils.py", line 13, in <listcomp>
    stopword = [line.strip() for line in f]
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2: ordinal not in range(128)

**Comment by zhanzecheng** [comment]
Hi BucherLi,
  这应该是你的系统是以ascii码作为默认编码，请设为utf-8.
Thanks,
Zecheng
